@php($isEnglish = app()->isLocale('en'))
<x-layouts.app>
@push('head')<script type="application/ld+json">{!! json_encode(['@@context'=>'https://schema.org','@@type'=>'Person','name'=>'Kareem Shalaby','alternateName'=>'كريم شلبي','jobTitle'=>'Software Engineer','url'=>url('/')], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>@endpush
<section class="container-site grid min-h-[72vh] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]">
<div><p class="mb-5 font-display text-sm font-bold uppercase tracking-[.22em] text-brand">Software Engineer · Entrepreneur · Writer</p><h1 class="max-w-4xl text-5xl leading-[1.22] font-bold tracking-tight sm:text-7xl">{!! $isEnglish ? 'I build, learn,<br><span class="text-brand">then write what matters.</span>' : 'أبني، أتعلّم،<br><span class="text-brand">ثم أكتب ما يستحق.</span>' !!}</h1><p class="mt-7 max-w-2xl text-xl leading-9 text-ink/65">{{ $isEnglish ? 'I’m Kareem Shalaby. I write about software, business, science, and lessons from real experience — clearly and honestly.' : 'أنا كريم شلبي. أكتب عن البرمجة، الأعمال، وما أتعلمه في العلوم والخبرات — بوضوح وصدق ومن أرض الواقع.' }}</p><div class="mt-9 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('articles.index') }}">{{ $isEnglish ? 'Explore articles →' : 'استكشف المقالات ←' }}</a><a class="btn-secondary" href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a></div></div>
<div class="relative"><div class="absolute -inset-5 -z-10 rotate-3 rounded-[3rem] bg-brand/10"></div><div class="rounded-[2.5rem] bg-ink p-9 text-white shadow-2xl"><div class="mb-16 flex items-center justify-between"><span class="font-display text-2xl font-bold">KS.</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs">CAIRO · EGYPT</span></div><p class="font-display text-3xl leading-relaxed">“المعرفة تصبح أثمن حين تتحول إلى شيء يمكن للآخرين البناء عليه.”</p><div class="mt-10 h-px bg-white/15"></div><p class="mt-5 text-sm text-white/50">Notes on software, business & a considered life.</p></div></div>
</section>
<section class="container-site py-16"><div class="mb-10 flex items-end justify-between"><div><p class="font-bold text-accent">{{ $isEnglish ? 'Knowledge paths' : 'مسارات المعرفة' }}</p><h2 class="mt-2 text-3xl font-bold">{{ $isEnglish ? 'Six fields I write about' : 'أكتب في ستة عوالم' }}</h2></div></div><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">@foreach($categories as $category)<a href="{{ route('articles.index',['category'=>$category->slug]) }}" class="card group transition hover:-translate-y-1 hover:border-accent"><div class="mb-7 flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-wider text-accent">{{ $category->name_en }}</span><span class="text-xs text-muted">{{ $category->articles_count }} {{ $isEnglish ? 'articles' : 'مقال' }}</span></div><h3 class="text-2xl font-bold group-hover:text-accent">{{ $category->name() }}</h3><p class="mt-3 leading-7 text-muted">{{ $category->description() }}</p></a>@endforeach</div></section>
@if($featured)<section class="container-site py-16"><div class="overflow-hidden rounded-[2.5rem] bg-brand text-white">@if($featured->cover_image)<a href="{{ route('articles.show',$featured) }}"><img class="aspect-[16/7] w-full object-cover" src="{{ asset('storage/'.$featured->cover_image) }}" alt="{{ $featured->title() }}"></a>@endif<div class="grid gap-10 p-8 sm:p-12 lg:grid-cols-[.7fr_1.3fr]"><div><span class="rounded-full bg-white/15 px-4 py-2 text-sm">{{ $isEnglish ? 'Featured' : 'اختيار مميز' }}</span><p class="mt-7 text-sm text-white/65">{{ $featured->category->name() }} · {{ $featured->published_at->translatedFormat('j F Y') }}</p></div><div><h2 class="text-3xl leading-snug font-bold sm:text-4xl">{{ $featured->title() }}</h2><p class="mt-4 text-lg leading-8 text-white/75">{{ $featured->excerpt() }}</p><a href="{{ route('articles.show',$featured) }}" class="mt-7 inline-block font-bold">{{ $isEnglish ? 'Read article →' : 'اقرأ المقال ←' }}</a></div></div></div></section>@endif
<section class="container-site py-16"><div class="mb-8 flex items-end justify-between"><div><p class="font-bold text-brand">{{ $isEnglish ? 'Recently' : 'حديثًا' }}</p><h2 class="mt-2 text-3xl font-bold">{{ $isEnglish ? 'Latest writing' : 'آخر ما كتبت' }}</h2></div><a class="font-bold text-brand" href="{{ route('articles.index') }}">{{ $isEnglish ? 'All articles →' : 'كل المقالات ←' }}</a></div><div class="grid gap-5 md:grid-cols-3">@foreach($articles->take(3) as $article)<article class="card overflow-hidden !p-0">@if($article->cover_image)<a href="{{ route('articles.show',$article) }}"><img class="aspect-video w-full object-cover" src="{{ asset('storage/'.$article->cover_image) }}" alt="{{ $article->title() }}" loading="lazy"></a>@endif<div class="p-6"><span class="text-xs font-bold text-brand">{{ $article->category->name() }}</span><h3 class="mt-4 text-xl leading-relaxed font-bold"><a href="{{ route('articles.show',$article) }}">{{ $article->title() }}</a></h3><p class="mt-3 line-clamp-2 text-sm leading-7 text-ink/55">{{ $article->excerpt() }}</p></div></article>@endforeach</div></section>
<section id="about" class="container-site py-20"><div class="grid gap-10 border-y border-ink/10 py-16 lg:grid-cols-2"><h2 class="text-4xl leading-snug font-bold">{!! $isEnglish ? 'A place to think clearly,<br>not to perform certainty.' : 'مساحة للتفكير بصوت واضح،<br>لا لاستعراض الإجابات.' !!}</h2><div class="space-y-5 text-lg leading-9 text-ink/65">@if($isEnglish)<p>I document tested lessons and questions I am still exploring. In family topics, I write from the perspective of what I learn and apply; in Islamic topics, I carefully cite sources and clarify the limits of my knowledge.</p><p>The professional profile separately collects technical writing, business case studies, projects, and experience for companies and clients.</p>@else<p>أوثّق هنا الدروس التي اختبرتها، والأسئلة التي ما زلت أبحث فيها. في موضوعات الأسرة أكتب دائمًا بصيغة «ما أتعلمه وأطبقه»، وفي الموضوعات الشرعية أعتني بالمصادر وحدود ما أنسبه لنفسي.</p><p>أما الملف المهني فيجمع المحتوى التقني ودراسات الأعمال والمشاريع في صفحة مستقلة يسهل مشاركتها مع الشركات والعملاء.</p>@endif</div></div></section>
</x-layouts.app>
