@php
    $isEnglish = app()->isLocale('en');
    $otherLocale = $isEnglish ? 'ar' : 'en';
    $switchParameters = array_merge(request()->route()->parameters(), ['locale' => $otherLocale]);
    $switchUrl = route(request()->route()->getName(), $switchParameters);
    if (request()->getQueryString()) $switchUrl .= '?'.request()->getQueryString();
@endphp
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ $isEnglish ? 'ltr' : 'rtl' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? ($isEnglish ? 'Kareem Shalaby | Software Engineer' : 'كريم شلبي | Kareem Shalaby') }}</title>
    <meta name="description" content="{{ $description ?? ($isEnglish ? 'Kareem Shalaby — Software Engineer, Entrepreneur, and Writer.' : 'كريم شلبي — مهندس برمجيات، رائد أعمال وكاتب. أكتب عن البرمجة والأعمال وما أتعلمه.') }}">
    <meta name="author" content="Kareem Shalaby"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
    <link rel="canonical" href="{{ $canonical ?? url()->current() }}">
    <meta property="og:type" content="{{ $ogType ?? 'website' }}"><meta property="og:title" content="{{ $title ?? 'كريم شلبي | Kareem Shalaby' }}">
    <meta property="og:description" content="{{ $description ?? ($isEnglish ? 'Writing about software, business, and life.' : 'مقالات في البرمجة والأعمال والحياة.') }}"><meta property="og:url" content="{{ $canonical ?? url()->current() }}"><meta property="og:locale" content="{{ $isEnglish ? 'en_US' : 'ar_EG' }}"><meta name="twitter:card" content="summary_large_image">
    <link rel="alternate" hreflang="{{ $otherLocale }}" href="{{ $switchUrl }}">
    @vite(['resources/css/app.css', 'resources/js/app.js']) @stack('head')
    @if(config('services.google.analytics_id'))<script async src="https://www.googletagmanager.com/gtag/js?id={{ config('services.google.analytics_id') }}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config',@json(config('services.google.analytics_id')),{'anonymize_ip':true});</script>@endif
</head>
<body class="grain min-h-screen antialiased">
<header class="sticky top-0 z-50 border-b border-line/80 bg-paper/90 backdrop-blur-xl"><div class="container-site flex h-24 items-center justify-between">
<a href="{{ route('home') }}" class="flex items-center gap-3" aria-label="{{ $isEnglish ? 'Kareem Shalaby home' : 'الصفحة الرئيسية لكريم شلبي' }}"><span class="grid h-16 w-[88px] place-items-center overflow-hidden rounded-2xl bg-[#08101d] p-1 shadow-lg shadow-brand/10"><img class="h-full w-full object-contain" src="{{ asset('ks.png') }}" alt="Kareem Shalaby"></span></a>
<nav class="hidden items-center gap-1 text-sm font-bold md:flex"><a class="nav-link {{ request()->routeIs('home') ? 'nav-link-active' : '' }}" href="{{ route('home') }}">{{ $isEnglish ? 'Home' : 'الرئيسية' }}</a><a class="nav-link {{ request()->routeIs('articles.*') ? 'nav-link-active' : '' }}" href="{{ route('articles.index') }}">{{ $isEnglish ? 'Articles' : 'المقالات' }}</a><a class="nav-link {{ request()->routeIs('projects.*') ? 'nav-link-active' : '' }}" href="{{ route('projects.index') }}">{{ $isEnglish ? 'Projects' : 'المشاريع' }}</a><a class="nav-link {{ request()->routeIs('professional') ? 'nav-link-active' : '' }}" href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a><a class="btn-primary ms-2 !px-5 !py-2.5" href="{{ route('contact.create') }}">{{ $isEnglish ? 'Contact me' : 'تواصل معي' }}</a></nav>
<button type="button" data-menu-toggle class="rounded-xl border border-ink/15 p-2 md:hidden" aria-label="{{ $isEnglish ? 'Open menu' : 'فتح القائمة' }}">☰</button></div>
<nav data-mobile-menu class="container-site hidden border-t border-line py-5 md:hidden"><div class="flex flex-col gap-4 font-bold"><a href="{{ route('home') }}">{{ $isEnglish ? 'Home' : 'الرئيسية' }}</a><a href="{{ route('articles.index') }}">{{ $isEnglish ? 'Articles' : 'المقالات' }}</a><a href="{{ route('projects.index') }}">{{ $isEnglish ? 'Projects' : 'المشاريع' }}</a><a href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a><a class="text-accent" href="{{ route('contact.create') }}">{{ $isEnglish ? 'Contact me' : 'تواصل معي' }}</a></div></nav></header>
<main>{{ $slot }}</main>
<footer class="mt-24 bg-[#0b1424] text-white"><div class="container-site grid gap-10 py-16 md:grid-cols-2 lg:grid-cols-4"><div><img class="h-28 w-auto" src="{{ asset('ks.png') }}" alt="Kareem Shalaby"><p class="mt-5 max-w-sm leading-7 text-white/55">{{ $isEnglish ? 'Software Engineer, Entrepreneur, and Writer. I share what I learn from work and life.' : 'مهندس برمجيات، رائد أعمال وكاتب. أشارك ما أتعلمه من العمل والحياة.' }}</p></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Categories' : 'الأقسام' }}</h2><div class="mt-5 grid gap-3 text-sm text-white/65">@foreach($footerCategories as $category)<a class="hover:text-accent" href="{{ route('articles.index',['category'=>$category->slug]) }}">{{ $category->name() }}</a>@endforeach</div></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Latest articles' : 'آخر المقالات' }}</h2><div class="mt-5 grid gap-4 text-sm text-white/65">@foreach($footerArticles as $article)<a class="leading-6 hover:text-accent" href="{{ route('articles.show',$article) }}">{{ $article->title() }}</a>@endforeach</div></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Get in touch' : 'تواصل معي' }}</h2><div class="mt-5 grid gap-3 text-sm text-white/65"><a dir="ltr" href="tel:{{ preg_replace('/\s+/','',$contactSettings['phone'] ?? '+20 101 925 1504') }}">{{ $contactSettings['phone'] ?? '+20 101 925 1504' }}</a>@if($contactSettings['phone_secondary'] ?? null)<a dir="ltr" href="tel:{{ preg_replace('/\s+/','',$contactSettings['phone_secondary']) }}">{{ $contactSettings['phone_secondary'] }}</a>@endif<a href="mailto:{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}">{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}</a>@foreach($socialLinks as $link)<a class="hover:text-accent" href="{{ $link->url }}" target="_blank" rel="noopener">{{ $link->label }} ↗</a>@endforeach<a class="font-bold text-accent" href="{{ route('contact.create') }}">{{ $isEnglish ? 'Send a message →' : 'أرسل رسالة ←' }}</a></div></div></div><div class="border-t border-white/10"><div class="container-site flex flex-col gap-3 py-6 text-xs text-white/40 sm:flex-row sm:justify-between"><p>© {{ date('Y') }} Kareem Shalaby. {{ $isEnglish ? 'All rights reserved.' : 'جميع الحقوق محفوظة.' }}</p><div class="flex gap-4"><a href="{{ route('sitemap') }}">Sitemap</a><a href="{{ route('admin.login') }}">{{ $isEnglish ? 'Admin' : 'الإدارة' }}</a></div></div></div></footer>
</body></html>
