@php
    $isEnglish = app()->isLocale('en');
    $otherLocale = $isEnglish ? 'ar' : 'en';
    $switchParameters = array_merge(request()->route()->parameters(), ['locale' => $otherLocale]);
    $switchUrl = route(request()->route()->getName(), $switchParameters);
    if (request()->getQueryString()) $switchUrl .= '?'.request()->getQueryString();
@endphp
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ $isEnglish ? 'ltr' : 'rtl' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? ($isEnglish ? 'Kareem Shalaby | Software Engineer' : 'كريم شلبي | Kareem Shalaby') }}</title>
    <meta name="description" content="{{ $description ?? ($isEnglish ? 'Kareem Shalaby — Software Engineer, Entrepreneur, and Writer.' : 'كريم شلبي — مهندس برمجيات، رائد أعمال وكاتب. أكتب عن البرمجة والأعمال وما أتعلمه.') }}">
    <meta name="author" content="Kareem Shalaby"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
    <link rel="canonical" href="{{ $canonical ?? url()->current() }}">
    <meta property="og:type" content="{{ $ogType ?? 'website' }}"><meta property="og:title" content="{{ $title ?? 'كريم شلبي | Kareem Shalaby' }}">
    <meta property="og:description" content="{{ $description ?? ($isEnglish ? 'Writing about software, business, and life.' : 'مقالات في البرمجة والأعمال والحياة.') }}"><meta property="og:url" content="{{ $canonical ?? url()->current() }}"><meta property="og:locale" content="{{ $isEnglish ? 'en_US' : 'ar_EG' }}"><meta name="twitter:card" content="summary_large_image"><script>if(localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme:dark)').matches)){document.documentElement.classList.add('dark')}</script>
    <link rel="alternate" hreflang="{{ $otherLocale }}" href="{{ $switchUrl }}">
    @vite(['resources/css/app.css', 'resources/js/app.js']) @stack('head')
    @if(config('services.google.analytics_id'))<script async src="https://www.googletagmanager.com/gtag/js?id={{ config('services.google.analytics_id') }}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config',@json(config('services.google.analytics_id')),{'anonymize_ip':true});</script>@endif
</head>
<body class="grain min-h-screen antialiased">
<header class="sticky top-0 z-50 border-b border-line bg-paper/90 backdrop-blur-xl"><div class="container-site flex h-20 items-center justify-between">
<a href="{{ route('home') }}" class="font-display text-lg font-bold tracking-tight">{{ $isEnglish ? 'Kareem Shalaby' : 'كريم شلبي' }} <span class="text-brand">/ KS</span></a>
<nav class="hidden items-center gap-5 text-sm font-bold md:flex"><a class="hover:text-accent" href="{{ route('articles.index') }}">{{ $isEnglish ? 'Articles' : 'المقالات' }}</a><a class="hover:text-accent" href="{{ route('projects.index') }}">{{ $isEnglish ? 'Projects' : 'المشاريع' }}</a><a class="hover:text-accent" href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a><a class="hover:text-accent" href="{{ route('home') }}#about">{{ $isEnglish ? 'About' : 'عني' }}</a><a class="rounded-full border border-accent/40 px-3 py-2 text-accent hover:bg-accent/10" href="{{ $switchUrl }}" hreflang="{{ $otherLocale }}">{{ $isEnglish ? 'العربية' : 'English' }}</a><button type="button" data-theme-toggle class="rounded-full border border-line bg-surface px-3 py-2" aria-label="{{ $isEnglish ? 'Toggle theme' : 'تبديل الوضع' }}">◐</button><a class="btn-primary !px-5 !py-2.5" href="mailto:{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}">{{ $isEnglish ? 'Contact me' : 'تواصل معي' }}</a></nav>
<button type="button" data-menu-toggle class="rounded-xl border border-ink/15 p-2 md:hidden" aria-label="{{ $isEnglish ? 'Open menu' : 'فتح القائمة' }}">☰</button></div>
<nav data-mobile-menu class="container-site hidden border-t border-line py-5 md:hidden"><div class="flex flex-col gap-4 font-bold"><a href="{{ route('articles.index') }}">{{ $isEnglish ? 'Articles' : 'المقالات' }}</a><a href="{{ route('projects.index') }}">{{ $isEnglish ? 'Projects' : 'المشاريع' }}</a><a href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a><a class="text-accent" href="{{ $switchUrl }}">{{ $isEnglish ? 'العربية' : 'English' }}</a><button type="button" data-theme-toggle class="text-start">◐ {{ $isEnglish ? 'Dark mode' : 'الوضع الليلي' }}</button><a href="mailto:{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}">{{ $isEnglish ? 'Contact me' : 'تواصل معي' }}</a></div></nav></header>
<main>{{ $slot }}</main>
<footer class="mt-24 border-t border-line bg-surface"><div class="container-site grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-4"><div><p class="font-display text-xl font-bold">{{ $isEnglish ? 'Kareem Shalaby' : 'كريم شلبي' }} <span class="text-accent">/ KS</span></p><p class="mt-4 leading-7 text-muted">{{ $isEnglish ? 'Software Engineer, Entrepreneur, and Writer. I share what I learn from work and life.' : 'مهندس برمجيات، رائد أعمال وكاتب. أشارك ما أتعلمه من العمل والحياة.' }}</p><div class="mt-5 space-y-2 text-sm"><a class="block hover:text-accent" dir="ltr" href="tel:{{ preg_replace('/\s+/','',$contactSettings['phone']??'') }}">{{ $contactSettings['phone'] ?? '+20 101 925 1504' }}</a><a class="block hover:text-accent" href="mailto:{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}">{{ $contactSettings['email'] ?? 'engkareemshalaby@gmail.com' }}</a>@foreach($socialLinks as $link)<a class="block hover:text-accent" href="{{ $link->url }}" target="_blank" rel="noopener">{{ $link->label }} ↗</a>@endforeach</div></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Categories' : 'الأقسام' }}</h2><div class="mt-5 grid gap-3 text-sm">@foreach($footerCategories as $category)<a class="hover:text-accent" href="{{ route('articles.index',['category'=>$category->slug]) }}">{{ $category->name() }}</a>@endforeach</div></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Latest articles' : 'آخر المقالات' }}</h2><div class="mt-5 grid gap-4 text-sm">@foreach($footerArticles as $article)<a class="leading-6 hover:text-accent" href="{{ route('articles.show',$article) }}">{{ $article->title() }}</a>@endforeach</div></div><div><h2 class="text-sm font-bold text-accent">{{ $isEnglish ? 'Quick links' : 'روابط سريعة' }}</h2><div class="mt-5 grid gap-3 text-sm"><a href="{{ route('professional') }}">{{ $isEnglish ? 'Professional Profile' : 'الملف المهني' }}</a><a href="{{ route('projects.index') }}">{{ $isEnglish ? 'Projects' : 'المشاريع' }}</a><a href="{{ route('articles.index') }}">{{ $isEnglish ? 'All articles' : 'كل المقالات' }}</a><a href="{{ route('sitemap') }}">Sitemap</a><a href="{{ route('admin.login') }}">{{ $isEnglish ? 'Admin' : 'الإدارة' }}</a></div></div></div><div class="border-t border-line"><div class="container-site flex flex-col gap-3 py-6 text-xs text-muted sm:flex-row sm:justify-between"><p>© {{ date('Y') }} Kareem Shalaby. {{ $isEnglish ? 'All rights reserved.' : 'جميع الحقوق محفوظة.' }}</p><p>{{ $contactSettings['location'] ?? 'Giza, Egypt' }}</p></div></div></footer>
</body></html>
