<x-layouts.app :title="$article->seo_title ?: $article->title().' | كريم شلبي'" :description="$article->seo_description ?: $article->excerpt()" :canonical="route('articles.show',$article)" og-type="article">
@push('head')<script type="application/ld+json">{!! json_encode(['@@context'=>'https://schema.org','@@type'=>'Article','headline'=>$article->title(),'description'=>$article->seo_description ?: $article->excerpt(),'datePublished'=>$article->published_at?->toIso8601String(),'dateModified'=>$article->updated_at->toIso8601String(),'author'=>['@@type'=>'Person','name'=>'Kareem Shalaby'],'mainEntityOfPage'=>route('articles.show',$article)], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>@endpush
@php($isEnglish = app()->isLocale('en'))
<article class="container-site py-16"><header class="mx-auto max-w-4xl text-center"><a href="{{ route('articles.index',['category'=>$article->category->slug]) }}" class="text-sm font-bold text-brand">{{ $article->category->name() }}</a><h1 class="mt-5 text-4xl leading-tight font-bold sm:text-6xl">{{ $article->title() }}</h1><p class="mx-auto mt-6 max-w-2xl text-xl leading-8 text-ink/60">{{ $article->excerpt() }}</p><div class="mt-7 text-sm text-ink/45">{{ $isEnglish ? 'Kareem Shalaby' : 'كريم شلبي' }} · {{ $article->published_at->translatedFormat('j F Y') }} · {{ max(1,ceil(str_word_count(strip_tags($article->body()))/220)) }} {{ $isEnglish ? 'min read' : 'دقائق قراءة' }}</div>@if($article->tags->isNotEmpty())<div class="mt-6 flex flex-wrap justify-center gap-2">@foreach($article->tags as $tag)<a class="rounded-full border border-accent/40 bg-accent/10 px-3 py-1.5 text-sm font-bold text-accent" href="{{ route('articles.index',['tag'=>$tag->slug]) }}">#{{ $tag->name }}</a>@endforeach</div>@endif</header>
@if($article->cover_image)<img class="mx-auto mt-12 aspect-video w-full max-w-5xl rounded-3xl object-cover shadow-lg" src="{{ asset('storage/'.$article->cover_image) }}" alt="{{ $article->title() }}">@endif
<div class="prose-kareem mx-auto mt-14 max-w-3xl">{!! Str::markdown($article->body(), ['html_input'=>'strip','allow_unsafe_links'=>false]) !!}</div>
</article>
@if($related->isNotEmpty())<section class="container-site"><div class="border-t border-ink/10 pt-12"><h2 class="text-2xl font-bold">{{ $isEnglish ? 'You may also like' : 'قد يهمك أيضًا' }}</h2><div class="mt-7 grid gap-4 md:grid-cols-3">@foreach($related as $item)<a class="card" href="{{ route('articles.show',$item) }}"><span class="text-xs text-brand">{{ $item->category->name() }}</span><h3 class="mt-3 text-lg leading-relaxed font-bold">{{ $item->title() }}</h3></a>@endforeach</div></div></section>@endif
</x-layouts.app>
